### ISSUE TITLE
Проблема с кодировкой

### ISSUE THREAD

**Issue by AlekseyUtkin** [tatarintsevvv/panorama#1]
Не корректно отображаются символы

![image](https://user-images.githubusercontent.com/43173437/45684153-18a35280-bb4e-11e8-8388-0710d68d8c83.png)

**Comment by AlekseyUtkin** [comment]
Прилагаю тестовый файл, для проверки у Вас.
[test.zip](https://github.com/tatarintsevvv/panorama/files/2392427/test.zip)

**Comment by AlekseyUtkin** [comment]
![image](https://user-images.githubusercontent.com/43173437/45693629-32509400-bb66-11e8-98f7-ec248c86a633.png)

под windows тоже самое

**Comment by tatarintsevvv** [comment]
Решил, по всей видимости, ошибку с кодировкой файлов. Добавил проверку версии OS и конвертирую строку для Windows и Мак.
